### ISSUE TITLE
[feature]: Automatically add file extensions to export paths

### ISSUE THREAD

**Issue by ramen** [TeamAudio/reaspeech#104]
### Feature Description

If a file extension is not entered for the export filename, the file is currently saved with no extension. Instead, add an extension based on the export file type (.json for JSON, .srt for SRT, etc.)

### Use Case

Files without extensions are difficult to work with in some operating systems. It's normally expected that the extension will be automatically added upon save.

### Additional Context

It might be worth creating a PathUtils library to share path-related functions.

**Comment by mikeylove** [comment]
maybe an "add extension" checkbox (default checked)? on save, look for an extensionless filename and if that's checked then add the extension.
