### ISSUE TITLE
[bug]: Recurring ReaScript Error: "=?:-1: ImGui_PushFont: expected a valid ImGui_Context*, got 0x60000301d5c0"

### ISSUE THREAD

**Issue by BPBaker** [TeamAudio/reaspeech#122]
### Operating System

macOS

### Other Operating System

MacOS Sequoia 

### Architecture

arm64

### ReaSpeech Image

reaspeech (CPU)

### What were you trying to do?

I've been getting this ReaScript error lately. "=?:-1: ImGui_PushFont: expected a valid ImGui_Context*, got 0x60000301d5c0" 

### What actually happened?

It seemed to only happen on one of my portable Reaper installations, but now it's happening to my all the time now on all my installations of Reaper...

### Steps to Reproduce

I thought I fixed it previously by reinstalling the docker image and the lua script. But I just tried that again and still get the error. Docker is running, localhosts 9000 is working, and I also reinstalled ReaImGui for good measure. It's also happening on a fresh install of Reaper.

**Comment by ramen** [comment]
Thanks for reporting! I'm able to reproduce this on Sequoia. It seems to happen intermittently, but especially often if I launch ReaSpeech from the Actions browser. I think this is a race condition related to the way ReaSpeech loads information about the ASR engine (faster-whisper or openai-whisper) at startup.

Will hopefully have a fix up shortly; in the meantime, a workaround might be to use version 0.4.0
